# Generated by Django 5.0.1 on 2024-02-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Royal_hotels', '0006_auto_20200808_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(default='Royal_hotels', max_length=30),
        ),
    ]
