# Generated by Django 5.0.1 on 2024-02-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Royal_hotels', '0007_alter_hotels_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(default='krishna', max_length=30),
        ),
    ]
